/* ===================================================================
   i18n7 — Onboarding feature-tour pages + "Choose your plan" paywall.
   Merged into CF_UI_MAP so tr()/trf() resolve them.
   =================================================================== */
Object.assign(CF_UI_MAP, {
  /* ---- tour: journal ---- */
  "Journal & daily check-in": { es:"Diario y registro diario", ca:"Diari i registre diari", fr:"Journal et bilan quotidien", de:"Tagebuch & täglicher Check-in", it:"Diario e check-in giornaliero", pt:"Diário e registro diário" },
  "Log your day in seconds — pain, energy, sleep, habits — and watch patterns appear in your charts.": { es:"Registra tu día en segundos (dolor, energía, sueño, hábitos) y observa cómo aparecen patrones en tus gráficos.", ca:"Registra el teu dia en segons (dolor, energia, son, hàbits) i mira com apareixen patrons als teus gràfics.", fr:"Enregistrez votre journée en quelques secondes — douleur, énergie, sommeil, habitudes — et regardez les tendances apparaître dans vos graphiques.", de:"Erfasse deinen Tag in Sekunden — Schmerz, Energie, Schlaf, Gewohnheiten — und sieh, wie Muster in deinen Diagrammen sichtbar werden.", it:"Registra la tua giornata in pochi secondi (dolore, energia, sonno, abitudini) e guarda emergere gli schemi nei tuoi grafici.", pt:"Registre seu dia em segundos — dor, energia, sono, hábitos — e veja padrões aparecerem nos seus gráficos." },
  "Coloured calendar of your days": { es:"Calendario coloreado de tus días", ca:"Calendari acolorit dels teus dies", fr:"Calendrier coloré de vos journées", de:"Farbiger Kalender deiner Tage", it:"Calendario colorato delle tue giornate", pt:"Calendário colorido dos seus dias" },
  "Charts for every parameter": { es:"Gráficos de cada parámetro", ca:"Gràfics de cada paràmetre", fr:"Graphiques pour chaque paramètre", de:"Diagramme für jeden Parameter", it:"Grafici per ogni parametro", pt:"Gráficos de cada parâmetro" },
  "PDF report for your doctor": { es:"Informe PDF para tu médico", ca:"Informe PDF per al teu metge", fr:"Rapport PDF pour votre médecin", de:"PDF-Bericht für deinen Arzt", it:"Report PDF per il tuo medico", pt:"Relatório PDF para seu médico" },
  /* ---- tour: food scan ---- */
  "Food scan": { es:"Escáner de comidas", ca:"Escàner de menjars", fr:"Scan des repas", de:"Essens-Scan", it:"Scanner dei pasti", pt:"Scan de refeições" },
  "Snap your plate — we estimate portion, calories and nutrients, then forget the photo.": { es:"Fotografía tu plato: estimamos ración, calorías y nutrientes, y luego olvidamos la foto.", ca:"Fotografia el teu plat: estimem ració, calories i nutrients, i després oblidem la foto.", fr:"Photographiez votre assiette : nous estimons la portion, les calories et les nutriments, puis nous oublions la photo.", de:"Fotografiere deinen Teller — wir schätzen Portion, Kalorien und Nährstoffe und vergessen dann das Foto.", it:"Fotografa il piatto: stimiamo porzione, calorie e nutrienti, poi dimentichiamo la foto.", pt:"Fotografe seu prato — estimamos porção, calorias e nutrientes, e depois esquecemos a foto." },
  "Calories & nutrients in seconds": { es:"Calorías y nutrientes en segundos", ca:"Calories i nutrients en segons", fr:"Calories et nutriments en secondes", de:"Kalorien & Nährstoffe in Sekunden", it:"Calorie e nutrienti in pochi secondi", pt:"Calorias e nutrientes em segundos" },
  "Gut-friendliness tags": { es:"Etiquetas de tolerancia intestinal", ca:"Etiquetes de tolerància intestinal", fr:"Étiquettes de tolérance intestinale", de:"Darmfreundlichkeits-Hinweise", it:"Etichette di tolleranza intestinale", pt:"Etiquetas de tolerância intestinal" },
  "Photos are never stored": { es:"Las fotos nunca se guardan", ca:"Les fotos mai es desen", fr:"Les photos ne sont jamais conservées", de:"Fotos werden nie gespeichert", it:"Le foto non vengono mai salvate", pt:"As fotos nunca são armazenadas" },
  /* ---- tour: medication ---- */
  "Alarms with snooze": { es:"Alarmas con repetición", ca:"Alarmes amb repetició", fr:"Alarmes avec rappel", de:"Wecker mit Schlummern", it:"Sveglie con posticipo", pt:"Alarmes com soneca" },
  "Low-stock refill alerts": { es:"Avisos de reposición", ca:"Avisos de reposició", fr:"Alertes de stock faible", de:"Nachschub-Warnungen", it:"Avvisi di scorte basse", pt:"Alertas de reposição" },
  "Adherence streaks": { es:"Rachas de adherencia", ca:"Ratxes d'adherència", fr:"Séries d'observance", de:"Therapietreue-Serien", it:"Serie di aderenza", pt:"Sequências de adesão" },
  /* ---- tour: community ---- */
  "Community & chats": { es:"Comunidad y chats", ca:"Comunitat i xats", fr:"Communauté et discussions", de:"Community & Chats", it:"Comunità e chat", pt:"Comunidade e chats" },
  "Share experiences, comment on posts and chat 1-to-1 with people who truly get it.": { es:"Comparte experiencias, comenta publicaciones y chatea uno a uno con gente que de verdad te entiende.", ca:"Comparteix experiències, comenta publicacions i xateja un a un amb gent que de veritat t'entén.", fr:"Partagez vos expériences, commentez les publications et discutez en tête-à-tête avec des gens qui vous comprennent vraiment.", de:"Teile Erfahrungen, kommentiere Beiträge und chatte 1-zu-1 mit Menschen, die dich wirklich verstehen.", it:"Condividi esperienze, commenta i post e chatta uno a uno con persone che ti capiscono davvero.", pt:"Compartilhe experiências, comente publicações e converse individualmente com pessoas que realmente entendem." },
  "Posts by patients & doctors": { es:"Publicaciones de pacientes y médicos", ca:"Publicacions de pacients i metges", fr:"Publications de patients et médecins", de:"Beiträge von Patienten & Ärzten", it:"Post di pazienti e medici", pt:"Publicações de pacientes e médicos" },
  "Private chats with other CFs": { es:"Chats privados con otros CFs", ca:"Xats privats amb altres CFs", fr:"Discussions privées avec d'autres CF", de:"Private Chats mit anderen CFs", it:"Chat private con altri CF", pt:"Chats privados com outros CFs" },
  "Your posts are saved forever": { es:"Tus publicaciones se guardan para siempre", ca:"Les teves publicacions es desen per sempre", fr:"Vos publications sont conservées pour toujours", de:"Deine Beiträge bleiben für immer gespeichert", it:"I tuoi post restano salvati per sempre", pt:"Suas publicações ficam salvas para sempre" },
  /* ---- tour: doctors ---- */
  "Doctors & appointments": { es:"Médicos y citas", ca:"Metges i cites", fr:"Médecins et rendez-vous", de:"Ärzte & Termine", it:"Medici e appuntamenti", pt:"Médicos e consultas" },
  "Browse license-verified specialists, chat with them and request appointments — right from the app.": { es:"Explora especialistas con licencia verificada, chatea con ellos y pide citas desde la propia app.", ca:"Explora especialistes amb llicència verificada, xateja amb ells i demana cites des de la mateixa app.", fr:"Parcourez des spécialistes vérifiés, discutez avec eux et demandez des rendez-vous, directement depuis l'app.", de:"Finde lizenzgeprüfte Spezialisten, chatte mit ihnen und frage Termine an — direkt aus der App.", it:"Trova specialisti con licenza verificata, chatta con loro e richiedi appuntamenti direttamente dall'app.", pt:"Encontre especialistas verificados, converse com eles e peça consultas — direto do app." },
  "12 specialties, from GI to mind": { es:"12 especialidades, del digestivo a la mente", ca:"12 especialitats, del digestiu a la ment", fr:"12 spécialités, du digestif au mental", de:"12 Fachrichtungen, vom Darm bis zur Psyche", it:"12 specialità, dall'intestino alla mente", pt:"12 especialidades, do intestino à mente" },
  "Identity & license verified": { es:"Identidad y licencia verificadas", ca:"Identitat i llicència verificades", fr:"Identité et licence vérifiées", de:"Identität & Lizenz geprüft", it:"Identità e licenza verificate", pt:"Identidade e licença verificadas" },
  "Request appointments in two taps": { es:"Pide citas en dos toques", ca:"Demana cites en dos tocs", fr:"Demandez un rendez-vous en deux gestes", de:"Termine mit zwei Tipps anfragen", it:"Richiedi appuntamenti in due tocchi", pt:"Peça consultas em dois toques" },
  /* ---- tour: Dr. CF ---- */
  "Dr. CF — your AI companion": { es:"Dr. CF: tu compañero de IA", ca:"Dr. CF: el teu company d'IA", fr:"Dr CF — votre compagnon IA", de:"Dr. CF — dein KI-Begleiter", it:"Dr. CF: il tuo compagno IA", pt:"Dr. CF — seu companheiro de IA" },
  "Dr. CF reads your journal and medication and answers with insights about YOUR life — not generic advice.": { es:"Dr. CF lee tu diario y tu medicación y responde con análisis sobre TU vida, no consejos genéricos.", ca:"Dr. CF llegeix el teu diari i la teva medicació i respon amb anàlisis sobre la TEVA vida, no consells genèrics.", fr:"Dr CF lit votre journal et vos médicaments et répond avec des analyses sur VOTRE vie — pas des conseils génériques.", de:"Dr. CF liest dein Tagebuch und deine Medikamente und antwortet mit Einblicken zu DEINEM Leben — keine generischen Tipps.", it:"Dr. CF legge il tuo diario e i tuoi farmaci e risponde con analisi sulla TUA vita, non consigli generici.", pt:"Dr. CF lê seu diário e sua medicação e responde com análises sobre a SUA vida — não conselhos genéricos." },
  "Knows your whole history": { es:"Conoce todo tu historial", ca:"Coneix tot el teu historial", fr:"Connaît tout votre historique", de:"Kennt deine ganze Geschichte", it:"Conosce tutta la tua storia", pt:"Conhece todo o seu histórico" },
  "Spots lifestyle patterns": { es:"Detecta patrones de estilo de vida", ca:"Detecta patrons d'estil de vida", fr:"Repère les tendances de votre mode de vie", de:"Erkennt Lebensstil-Muster", it:"Individua schemi nello stile di vita", pt:"Identifica padrões de estilo de vida" },
  "Available 24/7, in your language": { es:"Disponible 24/7, en tu idioma", ca:"Disponible 24/7, en el teu idioma", fr:"Disponible 24h/24, dans votre langue", de:"Rund um die Uhr, in deiner Sprache", it:"Disponibile 24/7, nella tua lingua", pt:"Disponível 24/7, no seu idioma" },

  /* ---- plan / paywall ---- */
  "Choose your plan": { es:"Elige tu plan", ca:"Tria el teu pla", fr:"Choisissez votre forfait", de:"Wähle deinen Plan", it:"Scegli il tuo piano", pt:"Escolha seu plano" },
  "Start free. Cancel anytime.": { es:"Empieza gratis. Cancela cuando quieras.", ca:"Comença gratis. Cancel·la quan vulguis.", fr:"Commencez gratuitement. Annulez à tout moment.", de:"Starte kostenlos. Jederzeit kündbar.", it:"Inizia gratis. Annulla quando vuoi.", pt:"Comece grátis. Cancele quando quiser." },
  "Free trial enabled": { es:"Prueba gratis activada", ca:"Prova gratuïta activada", fr:"Essai gratuit activé", de:"Gratis-Test aktiviert", it:"Prova gratuita attivata", pt:"Teste grátis ativado" },
  "14 days of full access — no payment today": { es:"14 días de acceso completo, sin pagar hoy", ca:"14 dies d'accés complet, sense pagar avui", fr:"14 jours d'accès complet — aucun paiement aujourd'hui", de:"14 Tage voller Zugriff — heute keine Zahlung", it:"14 giorni di accesso completo, nessun pagamento oggi", pt:"14 dias de acesso completo — sem pagamento hoje" },
  "Yearly plan": { es:"Plan anual", ca:"Pla anual", fr:"Forfait annuel", de:"Jahresplan", it:"Piano annuale", pt:"Plano anual" },
  "BEST VALUE": { es:"MEJOR PRECIO", ca:"MILLOR PREU", fr:"MEILLEURE OFFRE", de:"BESTER PREIS", it:"PIÙ CONVENIENTE", pt:"MELHOR OFERTA" },
  "/ year": { es:"/ año", ca:"/ any", fr:"/ an", de:"/ Jahr", it:"/ anno", pt:"/ ano" },
  "that's just 5 US$ / month": { es:"solo 5 US$ / mes", ca:"només 5 US$ / mes", fr:"soit seulement 5 $US / mois", de:"nur 5 US$ / Monat", it:"solo 5 US$ / mese", pt:"apenas 5 US$ / mês" },
  "Everything unlocked: journal, food scan, doctors, Dr. CF and more.": { es:"Todo desbloqueado: diario, escáner de comidas, médicos, Dr. CF y más.", ca:"Tot desbloquejat: diari, escàner de menjars, metges, Dr. CF i més.", fr:"Tout est débloqué : journal, scan des repas, médecins, Dr CF et plus.", de:"Alles freigeschaltet: Tagebuch, Essens-Scan, Ärzte, Dr. CF und mehr.", it:"Tutto sbloccato: diario, scanner dei pasti, medici, Dr. CF e altro.", pt:"Tudo desbloqueado: diário, scan de refeições, médicos, Dr. CF e mais." },
  "Today": { es:"Hoy", ca:"Avui", fr:"Aujourd'hui", de:"Heute", it:"Oggi", pt:"Hoje" },
  "Full access to everything, free": { es:"Acceso completo a todo, gratis", ca:"Accés complet a tot, gratis", fr:"Accès complet à tout, gratuitement", de:"Voller Zugriff auf alles, kostenlos", it:"Accesso completo a tutto, gratis", pt:"Acesso completo a tudo, grátis" },
  "Day 12": { es:"Día 12", ca:"Dia 12", fr:"Jour 12", de:"Tag 12", it:"Giorno 12", pt:"Dia 12" },
  "We remind you before any charge": { es:"Te avisamos antes de cualquier cobro", ca:"T'avisem abans de qualsevol cobrament", fr:"Nous vous prévenons avant tout prélèvement", de:"Wir erinnern dich vor jeder Abbuchung", it:"Ti avvisiamo prima di qualsiasi addebito", pt:"Avisamos você antes de qualquer cobrança" },
  "Day 14": { es:"Día 14", ca:"Dia 14", fr:"Jour 14", de:"Tag 14", it:"Giorno 14", pt:"Dia 14" },
  "59,99 US$ / year — cancel anytime in Settings": { es:"59,99 US$ / año; cancela cuando quieras en Ajustes", ca:"59,99 US$ / any; cancel·la quan vulguis a Configuració", fr:"59,99 $US / an — annulez à tout moment dans Réglages", de:"59,99 US$ / Jahr — jederzeit in den Einstellungen kündbar", it:"59,99 US$ / anno; annulla quando vuoi nelle Impostazioni", pt:"59,99 US$ / ano — cancele quando quiser em Configurações" },
  "Start 14-day free trial": { es:"Empezar prueba gratis de 14 días", ca:"Comença la prova gratuïta de 14 dies", fr:"Commencer l'essai gratuit de 14 jours", de:"14-tägigen Gratis-Test starten", it:"Inizia la prova gratuita di 14 giorni", pt:"Iniciar teste grátis de 14 dias" },
  "Subscribe now · 59,99 US$ / year": { es:"Suscribirse ahora · 59,99 US$ / año", ca:"Subscriu-te ara · 59,99 US$ / any", fr:"S'abonner · 59,99 $US / an", de:"Jetzt abonnieren · 59,99 US$ / Jahr", it:"Abbonati ora · 59,99 US$ / anno", pt:"Assinar agora · 59,99 US$ / ano" },
  "No payment due today · Cancel anytime": { es:"Hoy no pagas nada · Cancela cuando quieras", ca:"Avui no pagues res · Cancel·la quan vulguis", fr:"Aucun paiement aujourd'hui · Annulez à tout moment", de:"Heute keine Zahlung · Jederzeit kündbar", it:"Oggi non paghi nulla · Annulla quando vuoi", pt:"Nada a pagar hoje · Cancele quando quiser" },
  "Restore purchase": { es:"Restaurar compra", ca:"Restaura la compra", fr:"Restaurer l'achat", de:"Kauf wiederherstellen", it:"Ripristina acquisto", pt:"Restaurar compra" },
  "Swipe through what you get": { es:"Descubre todo lo que tendrás", ca:"Descobreix tot el que tindràs", fr:"Découvrez tout ce qui vous attend", de:"Entdecke, was dich erwartet", it:"Scopri tutto quello che avrai", pt:"Descubra tudo o que você terá" },
});
